/* generated from model FSM */
/* generated by template core.Class*/

/* (c) https://github.com/MontiCore/monticore */
package fsm._od;

/* generated by template core.Imports*/

import java.util.*;
import java.util.function.*;
import java.util.stream.Stream;
import de.se_rwth.commons.logging.Log;
import de.monticore.ast.ASTNode;
import de.monticore.ast.Comment;
import de.se_rwth.commons.SourcePosition;
import de.monticore.symboltable.*;
import de.monticore.ast.ASTCNode;

/* generated by template core.Annotations*/
// empty template: no Annotation

 public  class FSM2OD  implements fsm._visitor.FSMVisitor2,fsm._visitor.FSMHandler {

    /* generated by template core.Attribute*/
 protected  fsm._visitor.FSMTraverser traverser ;

    /* generated by template core.Attribute*/
 protected  de.monticore.prettyprint.IndentPrinter pp ;

    /* generated by template core.Attribute*/
 protected  de.monticore.generating.templateengine.reporting.commons.ReportingRepository reporting ;

    /* generated by template core.Attribute*/
 protected  boolean printEmptyOptional = false;;

    /* generated by template core.Attribute*/
 protected  boolean printEmptyList = false;;


    /* generated by template core.Constructor*/
 public  FSM2OD(de.monticore.prettyprint.IndentPrinter printer,de.monticore.generating.templateengine.reporting.commons.ReportingRepository reporting)
 {
  /* generated by template _od.ConstructorOD*/
  this.reporting = reporting;
  this.pp = printer;
}


    /* generated by template core.Method*/
 public  void handle (fsm._ast.ASTFSM node)

 {
      /* generated by template _od.HandleOD*/


  String name = de.se_rwth.commons.StringTransformations.uncapitalize(reporting.getASTNodeNameFormatted(node));
  printObject(name, "fsm._ast.ASTFSM");
  pp.indent();
  String scopeName = de.se_rwth.commons.StringTransformations.uncapitalize(reporting.getScopeNameFormatted(node.getEnclosingScope()));
  pp.println("enclosingScope = " + scopeName + ";");
  printAttribute("name", String.valueOf(node.getName()));
  {
    Iterator<fsm._ast.ASTState> iter_states = node.getStateList().iterator();
    boolean isEmpty = true;
    if (iter_states.hasNext()) {
      pp.print("states");
      pp.print(" = [");
      pp.println("// *size: " + node.getStateList().size());
      pp.indent();
      isEmpty = false;
    } else if (printEmptyList) {
      pp.print("states");
      pp.println(" = [];");
    }
    boolean isFirst = true;
    while (iter_states.hasNext()) {
      if (!isFirst) {
        pp.println(",");
      }
      isFirst = false;
      iter_states.next().accept(getTraverser());
    }
    if (!isEmpty) {
      pp.println("];");
      pp.unindent();
    }
  }
  printAttribute("initialState", String.valueOf(node.getInitialState()));
  printAttribute("finalStates", String.valueOf(node.getFinalStatesList()));
  pp.unindent();
  pp.print("}");
}

    /* generated by template core.Method*/
 public  void handle (fsm._ast.ASTState node)

 {
      /* generated by template _od.HandleOD*/


  String name = de.se_rwth.commons.StringTransformations.uncapitalize(reporting.getASTNodeNameFormatted(node));
  printObject(name, "fsm._ast.ASTState");
  pp.indent();
  if (node.isPresentSymbol()) {
    String symName = de.se_rwth.commons.StringTransformations.uncapitalize(reporting.getSymbolNameFormatted(node.getSymbol()));
    pp.println("symbol = " + symName + ";");
  } else if (printEmptyOptional) {
    pp.println("symbol = absent;");
  }
  String scopeName = de.se_rwth.commons.StringTransformations.uncapitalize(reporting.getScopeNameFormatted(node.getEnclosingScope()));
  pp.println("enclosingScope = " + scopeName + ";");
  printAttribute("name", String.valueOf(node.getName()));
  {
    Iterator<fsm._ast.ASTTransition> iter_transitions = node.getTransitionList().iterator();
    boolean isEmpty = true;
    if (iter_transitions.hasNext()) {
      pp.print("transitions");
      pp.print(" = [");
      pp.println("// *size: " + node.getTransitionList().size());
      pp.indent();
      isEmpty = false;
    } else if (printEmptyList) {
      pp.print("transitions");
      pp.println(" = [];");
    }
    boolean isFirst = true;
    while (iter_transitions.hasNext()) {
      if (!isFirst) {
        pp.println(",");
      }
      isFirst = false;
      iter_transitions.next().accept(getTraverser());
    }
    if (!isEmpty) {
      pp.println("];");
      pp.unindent();
    }
  }
  pp.unindent();
  pp.print("}");
}

    /* generated by template core.Method*/
 public  void handle (fsm._ast.ASTTransition node)

 {
      /* generated by template _od.HandleOD*/


  String name = de.se_rwth.commons.StringTransformations.uncapitalize(reporting.getASTNodeNameFormatted(node));
  printObject(name, "fsm._ast.ASTTransition");
  pp.indent();
  String scopeName = de.se_rwth.commons.StringTransformations.uncapitalize(reporting.getScopeNameFormatted(node.getEnclosingScope()));
  pp.println("enclosingScope = " + scopeName + ";");
  printAttribute("name", String.valueOf(node.getName()));
  if (null != node.getInput()) {
    pp.print("input");
    pp.print(" = ");
    node.getInput().accept(getTraverser());
    pp.println(";");
  }
  if (null != node.getOutput()) {
    pp.print("output");
    pp.print(" = ");
    node.getOutput().accept(getTraverser());
    pp.println(";");
  }
  pp.unindent();
  pp.print("}");
}

    /* generated by template core.Method*/
 public  fsm._visitor.FSMTraverser getTraverser ()

 {
      /* generated by template methods.Get*/

return this.traverser;

}

    /* generated by template core.Method*/
 public  void setTraverser (fsm._visitor.FSMTraverser traverser)

 {
      /* generated by template methods.Set*/

this.traverser = traverser;

}

    /* generated by template core.Method*/
 protected  void printAttribute (String name,String value)

 {
      /* generated by template _od.PrintAttribute*/
  pp.print(name);
  pp.print(" = ");
  pp.print(value);
  pp.println(";");
}

    /* generated by template core.Method*/
 protected  void printObject (String objName,String objType)

 {
      /* generated by template _od.PrintObject*/
pp.print(objName);
pp.print(":");
pp.print(de.se_rwth.commons.Names.getSimpleName(objType));
pp.println(" {");
}

    /* generated by template core.Method*/
 public  String printObjectDiagram (String modelName,fsm._ast.ASTFSMNode node)

 {
      /* generated by template _od.PrintObjectDiagram*/
  pp.clearBuffer();
  pp.setIndentLength(2);
  pp.print("objectdiagram ");
  pp.print(modelName);
  pp.println(" {");
  pp.indent();
  node.accept(getTraverser());
  pp.print(";");
  pp.unindent();
  pp.println("}");
  return pp.getContent();
}

    /* generated by template core.Method*/
 public  boolean isPrintEmptyOptional ()

 {
      /* generated by template methods.Get*/

return this.printEmptyOptional;

}

    /* generated by template core.Method*/
 public  void setPrintEmptyOptional (boolean printEmptyOptional)

 {
      /* generated by template methods.Set*/

this.printEmptyOptional = printEmptyOptional;

}

    /* generated by template core.Method*/
 public  boolean isPrintEmptyList ()

 {
      /* generated by template methods.Get*/

return this.printEmptyList;

}

    /* generated by template core.Method*/
 public  void setPrintEmptyList (boolean printEmptyList)

 {
      /* generated by template methods.Set*/

this.printEmptyList = printEmptyList;

}

}
