/* generated from model FSM */
/* generated by template core.Class*/

/* (c) https://github.com/MontiCore/monticore */
package fsm._symboltable;

/* generated by template core.Imports*/

import java.util.*;
import java.util.function.*;
import java.util.stream.Stream;
import de.se_rwth.commons.logging.Log;
import de.monticore.ast.ASTNode;
import de.monticore.ast.Comment;
import de.se_rwth.commons.SourcePosition;
import de.monticore.symboltable.*;
import de.monticore.ast.ASTCNode;


 public  class FSMSymbols2Json  implements fsm._visitor.FSMVisitor2 {

    /* generated by template core.Attribute*/
 protected  de.monticore.symboltable.serialization.IDeSer scopeDeSer ;

    /* generated by template core.Attribute*/
 protected  fsm._symboltable.StateSymbolDeSer stateSymbolDeSer ;

    /* generated by template core.Attribute*/
 protected  de.monticore.symboltable.serialization.JsonPrinter printer ;

    /* generated by template core.Attribute*/
 protected  fsm._visitor.FSMTraverser traverser ;


    /* generated by template core.Constructor*/
 public  FSMSymbols2Json()
 {
  this(fsm.FSMMill.traverser(), new de.monticore.symboltable.serialization.JsonPrinter());
traverser.add4FSM(this);
traverser.add4MCCommonLiterals(new de.monticore.literals.mccommonliterals._symboltable.MCCommonLiteralsSymbols2Json(getTraverser(), getJsonPrinter()));
traverser.add4MCBasics(new de.monticore.mcbasics._symboltable.MCBasicsSymbols2Json(getTraverser(), getJsonPrinter()));
traverser.add4MCLiteralsBasis(new de.monticore.literals.mcliteralsbasis._symboltable.MCLiteralsBasisSymbols2Json(getTraverser(), getJsonPrinter()));

}

    /* generated by template core.Constructor*/
 public  FSMSymbols2Json(fsm._visitor.FSMTraverser traverser,de.monticore.symboltable.serialization.JsonPrinter printer)
 {
  this.printer = printer;
this.traverser = traverser;
init();
}


    /* generated by template core.Method*/
 public  de.monticore.symboltable.serialization.JsonPrinter getJsonPrinter ()

 {
      return this.printer;
}

    /* generated by template core.Method*/
 public  void setJsonPrinter (de.monticore.symboltable.serialization.JsonPrinter printer)

 {
      this.printer=printer;
}

    /* generated by template core.Method*/
 public  String serialize (fsm._symboltable.IFSMScope toSerialize)

 {
      /* generated by template _symboltable.serialization.symbols2Json.Serialize4Symbols2Json*/
this.getJsonPrinter().clearBuffer();
toSerialize.accept(this.getTraverser());
String serialized = this.getJsonPrinter().getContent();
return serialized;

}

    /* generated by template core.Method*/
 public  String serialize (fsm._symboltable.IFSMArtifactScope toSerialize)

 {
      /* generated by template _symboltable.serialization.symbols2Json.Serialize4Symbols2Json*/
this.getJsonPrinter().clearBuffer();
toSerialize.accept(this.getTraverser());
String serialized = this.getJsonPrinter().getContent();
return serialized;

}

    /* generated by template core.Method*/
 public  fsm._symboltable.IFSMArtifactScope deserialize (String serialized)

 {
      /* generated by template _symboltable.serialization.symbols2Json.Deserialize*/

de.monticore.symboltable.serialization.json.JsonObject scope =
  de.monticore.symboltable.serialization.JsonParser.parseJsonObject(serialized);
return (fsm._symboltable.IFSMArtifactScope) scopeDeSer.deserializeArtifactScope(scope);

}

    /* generated by template core.Method*/
 public  fsm._visitor.FSMTraverser getTraverser ()

 {
      /* generated by template methods.Get*/

return this.traverser;

}

    /* generated by template core.Method*/
 public  void setTraverser (fsm._visitor.FSMTraverser traverser)

 {
      /* generated by template methods.Set*/

this.traverser = traverser;

}

    /* generated by template core.Method*/
 public  void init ()

 {
      /* generated by template _symboltable.serialization.symbols2Json.Init*/

  fsm._symboltable.IFSMGlobalScope gs = fsm.FSMMill.globalScope();
  scopeDeSer = gs.getDeSer();
  stateSymbolDeSer = (fsm._symboltable.StateSymbolDeSer) gs.getSymbolDeSer("fsm._symboltable.StateSymbol");

}

    /* generated by template core.Method*/
 public  String getSerializedString ()

 {
      return getJsonPrinter().getContent();
}

    /* generated by template core.Method*/
 public  fsm._symboltable.IFSMArtifactScope load (java.net.URL url)

 {
      /* generated by template _symboltable.serialization.symbols2Json.Load2*/

//1. load content of file at given location as String
String serialized = de.monticore.io.FileReaderWriter.readFromFile(url);

//2. deserialize String to an artifact scope and add to enclosing scope
return this.deserialize(serialized);
}

    /* generated by template core.Method*/
 public  fsm._symboltable.IFSMArtifactScope load (java.io.Reader reader)

 {
      /* generated by template _symboltable.serialization.symbols2Json.Load2*/

//1. load content of file at given location as String
String serialized = de.monticore.io.FileReaderWriter.readFromFile(reader);

//2. deserialize String to an artifact scope and add to enclosing scope
return this.deserialize(serialized);
}

    /* generated by template core.Method*/
 public  fsm._symboltable.IFSMArtifactScope load (String model)

 {
      /* generated by template _symboltable.serialization.symbols2Json.Load2*/

//1. load content of file at given location as String
String serialized = de.monticore.io.FileReaderWriter.readFromFile(java.nio.file.Paths.get(model));

//2. deserialize String to an artifact scope and add to enclosing scope
return this.deserialize(serialized);
}

    /* generated by template core.Method*/
 public  String store (fsm._symboltable.IFSMArtifactScope scope,String fileName)

 {
      /* generated by template _symboltable.serialization.symbols2Json.Store*/

  getJsonPrinter().clearBuffer();
  scope.accept(getTraverser());
  String serialized = getJsonPrinter().getContent();
  de.monticore.io.FileReaderWriter.storeInFile(java.nio.file.Paths.get(fileName), serialized);
  return serialized;

}

    /* generated by template core.Method*/
 public  void visit (fsm._symboltable.IFSMScope node)

 {
      /* generated by template _symboltable.serialization.symbols2Json.VisitScope4STP*/

  if(getJsonPrinter().toString().isEmpty()){
    getJsonPrinter().beginObject();
  } else{
    getJsonPrinter().beginObject(de.monticore.symboltable.serialization.JsonDeSers.SPANNED_SCOPE);
  }
  scopeDeSer.serialize((de.monticore.symboltable.IScope) node, (FSMSymbols2Json) this);
  getJsonPrinter().beginArray(de.monticore.symboltable.serialization.JsonDeSers.SYMBOLS);


}

    /* generated by template core.Method*/
 public  void endVisit (fsm._symboltable.IFSMScope node)

 {
      /* generated by template _symboltable.serialization.symbols2Json.EndVisit4Scope*/

  getJsonPrinter().endArray();
  scopeDeSer.serializeAddons((de.monticore.symboltable.IScope) node, (FSMSymbols2Json) this);
  getJsonPrinter().endObject();


}

    /* generated by template core.Method*/
 public  void visit (fsm._symboltable.StateSymbol node)

 {
      /* generated by template _symboltable.serialization.symbols2Json.VisitSymbol*/

  stateSymbolDeSer.serialize(node, (FSMSymbols2Json) this);
}

    /* generated by template core.Method*/
 public  void visit (fsm._symboltable.IFSMArtifactScope node)

 {
      /* generated by template _symboltable.serialization.symbols2Json.VisitArtifactScope*/

  getJsonPrinter().beginObject();
  scopeDeSer.serialize((de.monticore.symboltable.IArtifactScope) node, (FSMSymbols2Json) this);
  getJsonPrinter().beginArray(de.monticore.symboltable.serialization.JsonDeSers.SYMBOLS);


}

    /* generated by template core.Method*/
 public  void endVisit (fsm._symboltable.IFSMArtifactScope node)

 {
      /* generated by template _symboltable.serialization.symbols2Json.EndVisit4Scope*/

  getJsonPrinter().endArray();
  scopeDeSer.serializeAddons((de.monticore.symboltable.IArtifactScope) node, (FSMSymbols2Json) this);
  getJsonPrinter().endObject();


}

}
