/* generated from model FSM */
/* generated by template core.Interface*/

/* (c) https://github.com/MontiCore/monticore */
package fsm._symboltable;

/* generated by template core.Imports*/

import java.util.*;
import java.util.function.*;
import java.util.stream.Stream;
import de.se_rwth.commons.logging.Log;
import de.monticore.ast.ASTNode;
import de.monticore.ast.Comment;
import de.se_rwth.commons.SourcePosition;
import de.monticore.symboltable.*;


 public  interface ICommonFSMSymbol extends de.monticore.symboltable.ISymbol  { 


  /* generated by template core.Method*/
 abstract  public  void accept (fsm._visitor.FSMTraverser visitor)

;
  /* generated by template core.Method*/
 abstract  public  fsm._symboltable.IFSMScope getEnclosingScope ()

;
  /* generated by template core.Method*/
 abstract  public  void setEnclosingScope (fsm._symboltable.IFSMScope enclosingScope)

;
}
