/* generated from model FSM */
/* generated by template core.Class*/

/* (c) https://github.com/MontiCore/monticore */
package fsm._ast;

/* generated by template core.Imports*/

import java.util.*;
import java.util.function.*;
import java.util.stream.Stream;
import de.se_rwth.commons.logging.Log;
import de.monticore.ast.ASTNode;
import de.monticore.ast.Comment;
import de.se_rwth.commons.SourcePosition;
import de.monticore.symboltable.*;
import de.monticore.ast.ASTCNode;


 public  class ASTConstantsFSM  {

    /* generated by template core.Attribute*/
 public  final  static  String LANGUAGE = "FSM";

    /* generated by template core.Attribute*/
 public  final  static  int DEFAULT = 0;

    /* generated by template core.Attribute*/
 public  static  String[] superGrammars = {"de.monticore.literals.MCCommonLiterals", "de.monticore.MCBasics", "de.monticore.literals.MCLiteralsBasis"};


    /* generated by template core.Constructor*/
 public  ASTConstantsFSM()
 {
  /* generated by template core.EmptyBody*/
// empty body

}


    /* generated by template core.Method*/
 public  static  Collection<String> getAllLanguages ()

 {
      /* generated by template _ast.ast_constants.GetAllLanguages*/


  Collection<String> allLanguages = com.google.common.collect.Sets.newLinkedHashSet();
    allLanguages.addAll(de.monticore.literals.mccommonliterals._ast.ASTConstantsMCCommonLiterals.getAllLanguages());
    allLanguages.addAll(de.monticore.mcbasics._ast.ASTConstantsMCBasics.getAllLanguages());
    allLanguages.addAll(de.monticore.literals.mcliteralsbasis._ast.ASTConstantsMCLiteralsBasis.getAllLanguages());
  allLanguages.add(LANGUAGE);
  return allLanguages;
}

}
