/* generated from model FSM */
/* generated by template core.Enum*/

/* (c) https://github.com/MontiCore/monticore */
package fsm._ast;

@Deprecated
public enum FSMLiterals
{

;

  /* generated by template core.Attribute*/
 protected  int intValue ;


  /* generated by template core.Constructor*/
 private  FSMLiterals(int intValue)
 {
  this.intValue = intValue;
}


  /* generated by template core.Method*/
 public  int getIntValue ()

 {
      /* generated by template methods.Get*/

return this.intValue;

}

}
